sudo: required
services: 
  - docker

before_install:
  - docker build -t okoyeapps/react-test -f ./client/Dockerfile.dev  ./client

script:
  - docker run okoyeapps/react-test npm test -- --coverage watchAll=false

after_success:
  - docker build -t okoyeapps/multi-client  ./client
  - docker build -t okoyeapps/multi-nginx  ./nginx
  - docker build -t okoyeapps/multi-server  ./server
  - docker build -t okoyeapps/multi-worker  ./worker
  #Log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take this images to Docker hub
  - docker push okoyeapps/multi-client
  - docker push okoyeapps/multi-nginx
  - docker push okoyeapps/multi-server
  - docker push okoyeapps/multi-worker
  

